# Optional release face. Source license is preserved under fonts/.
substitutions:
  project_ref: 0.5.3
  project_repo: sandro-defender/Esphome-Max7219-Matrix-Clock
  fonts_base_url: https://raw.githubusercontent.com/${project_repo}/${project_ref}/fonts
font:
- id: font_jersey_15_source
  file:
    type: web
    url: ${fonts_base_url}/jersey-15/Jersey15-Regular.ttf
  size: 15
  bpp: 1
  glyphs:
  - '0123456789:.-/%!?+ '

esphome:
  build_flags:
    - -DMAX7219_FONT_JERSEY_15

select:
  - id: !extend clock_font
    options:
      - "Jersey 15"
