# Optional release face. Source license is preserved under fonts/.
substitutions:
  project_ref: 0.4.0
  project_repo: sandro-defender/Esphome-Max7219-Matrix-Clock
  fonts_base_url: https://raw.githubusercontent.com/${project_repo}/${project_ref}/fonts
font:
- id: font_kdam_thmor_pro_source
  file:
    type: web
    url: ${fonts_base_url}/kdam-thmor-pro/KdamThmorPro-Regular.ttf
  size: 9
  bpp: 1
  glyphs:
  - '0123456789:.-/%!?+ '

esphome:
  build_flags:
    - -DMAX7219_FONT_KDAM_THMOR_PRO

select:
  - id: !extend clock_font
    options:
      - "Kdam Thmor Pro"
