# Matrix Sans Screen v1.800, a 5x7 square-dot LED face.
# Upstream source and SIL Open Font License 1.1: fonts/matrix-sans-screen/OFL.txt
font:
  - id: font_matrix_sans_screen_source
    file:
      type: web
      url: ${fonts_base_url}/matrix-sans-screen/MatrixSansScreen-Regular.ttf
    size: 8
    bpp: 1
    glyphs:
      - '0123456789:.-/%!?+ აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ'

esphome:
  build_flags:
    - -DMAX7219_FONT_MATRIX_SANS_SCREEN

select:
  - id: !extend clock_font
    options:
      - "Matrix Sans Screen"
