# Optional release face. Source license is preserved under fonts/.
font:
- id: font_matrix_2px_source
  file:
    type: web
    url: ${fonts_base_url}/matrix-2px/Matrix2px.ttf
  size: 8
  bpp: 1
  glyphs:
  - '0123456789:.-/%!?+ '

esphome:
  build_flags:
    - -DMAX7219_FONT_MATRIX_2PX

select:
  - id: !extend clock_font
    options:
      - "Matrix 2px"
