# Optional release face. Source license is preserved under fonts/.
substitutions:
  project_ref: 0.5.0
  project_repo: sandro-defender/Esphome-Max7219-Matrix-Clock
  fonts_base_url: https://raw.githubusercontent.com/${project_repo}/${project_ref}/fonts
font:
- id: font_matrix_2px_source
  file:
    type: web
    url: ${fonts_base_url}/matrix-2px/Matrix2px.ttf
  size: 8
  bpp: 1
  glyphs:
  - '0123456789:.-/%!?+ '

esphome:
  build_flags:
    - -DMAX7219_FONT_MATRIX_2PX

select:
  - id: !extend clock_font
    options:
      - "Matrix 2px"
