import { withFonts } from "./fontSelection";
import { fontSpec } from "./fontCatalog";
import { deviceSlug, nodeId } from "./device";
import { clampNumber, type Config } from "./types";

const PROJECT_REPOSITORY = "https://github.com/sandro-defender/Esphome-Max7219-Matrix-Clock";
// Must stay identical to examples/release.yaml and the released font packages
// (checked by tests/test_config.py: test_release_example_pins_tag_and_fonts).
const PROJECT_REF = "0.5.5";
export const INSTALLER_READY = true;

/** Must stay identical to examples/release.yaml (checked by tests/test_config.py). */
const PACKAGE_FILES = [
  "packages/base.yaml",
  "packages/network.yaml",
  "packages/renderer.yaml",
  "packages/display.yaml",
  "packages/controls.yaml",
  "packages/actions.yaml",
  "packages/diagnostics.yaml",
  "packages/ota_ui.yaml",
  "packages/web_server.yaml",
] as const;

function boundedInteger(value: number, minimum: number, maximum: number): number {
  return clampNumber(value, minimum, maximum);
}

function restoreMode(enabled: boolean): string {
  return enabled ? "RESTORE_DEFAULT_ON" : "RESTORE_DEFAULT_OFF";
}

export function sanitizeFriendly(name: string): string {
  const clean = name.replace(/["\\\r\n]/g, "").trim();
  return clean.slice(0, 48) || "MAX7219 Clock";
}

export function sanitizeTimezone(tz: string): string {
  const clean = tz.trim();
  if (/^[A-Za-z0-9_+\/-]+$/.test(clean)) return clean;
  return "UTC";
}

export function sanitizeEntity(id: string): string {
  return id.trim().toLowerCase();
}

/** Home Assistant "Clock font" option for the selected preview font. */
export function selectedFontOption(font: Config["clockFont"]): string {
  return fontSpec(font).option;
}

export function entityMap(cfg: Config) {
  const node = nodeId(cfg.deviceName);
  return {
    node,
    slug: deviceSlug(cfg.deviceName),
    screen: `select.${node}_screen`,
    alignment: `select.${node}_clock_alignment`,
    font: `select.${node}_clock_font`,
    seconds: `select.${node}_seconds_display`,
    dateFormat: `select.${node}_date_format`,
    scroll: `select.${node}_message_scroll`,
    brightness: `number.${node}_matrix_brightness`,
    duration: `number.${node}_default_message_duration`,
    scrollSpeed: `number.${node}_message_scroll_speed`,
    mode: `text_sensor.${node}_display_mode`,
    ota: `text_sensor.${node}_ota_state`,
    showAction: `esphome.${node}_show_message`,
    clearAction: `esphome.${node}_clear_message`,
    countdownAction: `esphome.${node}_start_countdown`,
  };
}

export function sampleAction(cfg: Config, message: string, hold = cfg.messageHold): string {
  const ids = entityMap(cfg);
  const safe = message.replace(/["\r\n]/g, "'");
  return `action: ${ids.showAction}\ndata:\n  message: "${safe}"\n  duration: ${boundedInteger(hold, 0, 3600)}`;
}

export function installCommand(cfg: Config): string {
  return `esphome run ${deviceSlug(cfg.deviceName)}.yaml`;
}

export function buildYaml(cfg: Config): string {
  cfg = withFonts(cfg, cfg.fonts);
  const deviceName = deviceSlug(cfg.deviceName);
  const friendlyName = sanitizeFriendly(cfg.friendlyName);
  const timezone = sanitizeTimezone(cfg.timezone);
  const chips = boundedInteger(cfg.chips, 1, 16);
  const rows = boundedInteger(cfg.rows, 1, 4);
  const packageFiles = [...PACKAGE_FILES, ...cfg.fonts.map((id) => `packages/fonts/${id}.yaml`)].map((file) => `      - ${file}`).join("\n");

  return `# MAX7219 Matrix Clock — one-file installer
# Generated by the Web Configurator.
# Keep this file beside secrets.yaml. ESPHome downloads the pinned modular
# firmware and bundled fonts directly from the project repository.

substitutions:
  # Credentials are resolved only from your local secrets.yaml.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_encryption_key: !secret api_encryption_key
  fallback_ap_password: !secret fallback_ap_password
  web_server_username: !secret web_server_username
  web_server_password: !secret web_server_password

  # Firmware and font assets use the same immutable release.
  project_ref: "${PROJECT_REF}"

  # Device identity and hardware.
  device_name: ${deviceName}
  friendly_name: "${friendlyName}"
  timezone: ${timezone}
  board: d1_mini
  matrix_clk_pin: ${cfg.clkPin}
  matrix_mosi_pin: ${cfg.mosiPin}
  matrix_cs_pin: ${cfg.csPin}
  matrix_chips: "${chips}"
  matrix_rows: "${rows}"
  matrix_wiring: ${cfg.wiring}
  matrix_rotate_chip: "${cfg.rotateChip}"
  matrix_flip_x: "${cfg.flipX}"

  # Boot defaults. Home Assistant can change these after installation.
  matrix_intensity: "${boundedInteger(cfg.brightness, 0, 15)}"
  matrix_night_intensity: "${boundedInteger(cfg.nightBrightness, 0, 15)}"
  animation_ms: "${boundedInteger(cfg.animationMs, 0, 2000)}"
  animation_row_gap: "${boundedInteger(cfg.animationRowGap, 0, 2)}"
  message_ms_per_px: "${boundedInteger(cfg.scrollSpeed, 20, 200)}"
  screen_cycle_interval: "${boundedInteger(cfg.cycleInterval, 5, 300)}"
  default_message_duration: "${boundedInteger(cfg.messageHold, 0, 3600)}"

packages:
  clock:
    url: ${PROJECT_REPOSITORY}
    ref: "${PROJECT_REF}"
    refresh: 1d
    files:
${packageFiles}

# Initial Home Assistant preferences. Restored values from an existing device
# take priority after the first boot.
select:
  - id: !extend screen_mode
    initial_option: "${cfg.screen}"
  - id: !extend clock_alignment
    initial_option: "${cfg.alignment}"
  - id: !extend time_format
    initial_option: "${cfg.hourFormat === "12-hour" ? "12 hour" : "24 hour"}"
  - id: !extend seconds_display
    initial_option: "${cfg.secondsMode}"
  - id: !extend date_format
    initial_option: "${cfg.dateFormat}"
  - id: !extend clock_font
    initial_option: "${selectedFontOption(cfg.clockFont)}"
  - id: !extend message_scroll_behavior
    initial_option: "${cfg.scrollMode}"

number:
  - id: !extend night_start_hour
    initial_value: ${boundedInteger(cfg.nightStart, 0, 23)}
  - id: !extend night_end_hour
    initial_value: ${boundedInteger(cfg.nightEnd, 0, 23)}
  - id: !extend animation_duration
    initial_value: ${boundedInteger(cfg.animationMs, 0, 2000)}
  - id: !extend animation_row_gap
    initial_value: ${boundedInteger(cfg.animationRowGap, 0, 2)}
  - id: !extend message_scroll_speed
    initial_value: ${boundedInteger(cfg.scrollSpeed, 20, 200)}
  - id: !extend screen_cycle_interval
    initial_value: ${boundedInteger(cfg.cycleInterval, 5, 300)}
  - id: !extend default_message_duration
    initial_value: ${boundedInteger(cfg.messageHold, 0, 3600)}

switch:
  - id: !extend matrix_display_power
    restore_mode: ${restoreMode(cfg.displayPower)}
  - id: !extend clock_blink
    restore_mode: ${restoreMode(cfg.blinkColon)}
  - id: !extend clock_animate
    restore_mode: ${restoreMode(cfg.digitAnimation)}
  - id: !extend auto_cycle
    restore_mode: ${restoreMode(cfg.autoCycle)}
  - id: !extend night_schedule_enabled
    restore_mode: ${restoreMode(cfg.nightDim)}
  - id: !extend display_inversion
    restore_mode: ${restoreMode(cfg.invert)}
`;
}
